---
title: "STAT 542 Final_Naive Bayes Analysis"
author: "Zhaoying Tang"
date: "December 13, 2015"
output: html_document
---

Naive Bayes
-----------------------------------------------------------------------------
As the data in Naive Bayes can't have 0 standard deviance in features, so we need to remove those feature which have 0 by class.


First, change all factor to numeric:

```{r,eval=FALSE}
setwd("C:\\Users\\ztang15\\Desktop\\542")
load("tnew5.RData")
load("test5.RData")

for (col in 1:ncol(tnew5)) if (class(tnew5[[col]])=="factor") tnew5[[col]] <- as.numeric(tnew5[[col]])
for (col in 1:ncol(test5)) if (class(test5[[col]])=="factor") test5[[col]] <- as.numeric(test5[[col]])
```

Second,put target in the last column:

```{r,eval=FALSE}
target=data.frame(tnew5$target)
tnew5$target=NULL

tnew5<-data.frame(tnew5,target)
colnames(tnew5)
colnames(tnew5)[1859]<-"target"
```

Third, delet deviance equals 0:
```{r,eval=FALSE}
newtrain=tnew5
class1=newtrain[newtrain$target==1,]
class0=newtrain[newtrain$target==0,]

variance=as.data.frame(apply(class1, 2, var))
rmvar=which(variance==0)
variance1=as.data.frame(apply(class0, 2, var))
rmvar2=which(variance1==0)

rm=c(447,448)

newtrain=newtrain[,-rm]
tnew5=newtrain
test5=test5[,-rm]
```

Then, we can train the model use Package "e1071"
```{r,eval=FALSE}
library(e1071)
NBfit.para=naiveBayes(as.factor(tnew5$target)~.,data = tnew5)
names(NBfit.para)
ytest.pred.NB.para=predict(NBfit.para,test5)
```
